sudo: required
dist: trusty
language: node_js
node_js:
  - 5.2.0
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64
  - sudo mv chromedriver /usr/bin
before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 5 # give xvfb some time to start
  - gulp bundle
  - npm start &
  - sleep 5
script: npm run test-travis
